# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c62cc045ddec8d5263344d693dac6b94ccf9a717f0e48de3a0c57888fe3f33ebc2796b396166b7f7f533841249694d8198f62fdfd86c82cacd8b0c13842ea5b0

test:
  secret_key_base: ad3bf3ebb694b81862e6d83d3cc7cbf0fa64898d2287523ae7a697063879f01279d67b39dae834411dd51ab6ca5189fc7649f5c487833da036bf7d96d650a1ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
